### ISSUE TITLE
Gaia in my Synology NAS

### ISSUE THREAD

**Issue by victorsnk** [stacks-network/gaia#291]
How can I install Gaia in my own Synology NAS? Is it possible?

**Comment by wileyj** [comment]
based on this: https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_container

It definitely seems possible, but I've not heard of anyone trying to run this on synology. 

I did some work on a docker-compose version of gaia a while back, it might be helpful here:
https://github.com/blockstackpbc/gaia-docker

there are also systemd unit-files to run each container as a standalone container. as long as synology gives you access to create a docker network and mount a filesystem to a container, I don't see any reason this wouldn't work. 


but the answer your question - the easiest way to do this would be running the gaia components as docker containers.

**Comment by criadoperez** [comment]
Question was answered so closing the issue.
