### ISSUE TITLE
Gaia was not accessible – GetFile and PutFile api was not working

### ISSUE THREAD

**Issue by ilayaperumalraja** [stacks-network/gaia#347]
**Describe the bug**
Gaia was not accessible and all requests to gaia were failing (request timeout) on 20-Sep morning. After an hour, it started working, since they reversed DNS changes. 

But we were facing the bug, while using BlockSurvey. Few of requests to gaia were successful and few were failed. Few PutFile request to gaia took long time and timed out. When we retried to save the same document, it threw 409 error (Concurrent write on same document). 

Can you please help us to understand, what happened during this time? 

**To Reproduce**
I attached the screenshot, when it was occurred. Now it is working.

**Expected behavior**
First putFile request to gaia should have been succussed. Or when we retried to save again, it should have been succussed.

**Screenshots**
 
![unknown](https://user-images.githubusercontent.com/30572289/134140460-4a912639-1662-4781-a840-bbd772562f4c.png)

**Comment by criadoperez** [comment]
I'm sorry you had some accessibility issues that morning.
It's already been some time since this happened so its very complicated to trace that particular day. I'm closing the issue but please let us know again if you encounter this issue or any other one again.
